let PhoneCodes = ({ onCodeChange }) => {
  return (
    <>
      <input list='area-codes' onChange={onCodeChange} className='px-1 rounded-md w-16 text-black' placeholder='País' />
      <datalist id='area-codes'>
        <option value=''></option>
        {/* <option value='AC'>AC</option> */}
        {/* <option value='AD'>Andorra</option> */}
        {/* <option value='AE'>AE</option> */}
        {/* <option value='AF'>Afganistan</option>
        <option value='AG'>Antigua </option>
        <option value='AI'>Anguila</option>
        <option value='AL'>Albania</option>
        <option value='AM'>AM</option>
        <option value='AO'>Angola</option> */}
        <option value='AR'>Argentina</option>
        {/* <option value='AS'>Samoa Americana</option> */}
        {/* <option value='AT'>AT</option>
        <option value='AU'>AU</option>
        <option value='AW'>AW</option>
        <option value='AX'>AX</option>
        <option value='AZ'>AZ</option>
        <option value='BA'>BA</option>
        <option value='BB'>BB</option>
        <option value='BD'>BD</option>
        <option value='BE'>BE</option>
        <option value='BF'>BF</option>
        <option value='BG'>BG</option>
        <option value='BH'>BH</option>
        <option value='BI'>BI</option>
        <option value='BJ'>BJ</option>
        <option value='BL'>BL</option>
        <option value='BM'>BM</option>
        <option value='BN'>BN</option> */}
        <option value='BO'>Bolivia</option>
        {/* <option value='BQ'>BQ</option> */}
        <option value='BR'>Brasil</option>
        {/* <option value='BS'>BS</option>
        <option value='BT'>BT</option>
        <option value='BW'>BW</option>
        <option value='BY'>BY</option> */}
        <option value='BZ'>Belice</option>
        <option value='CA'>Canada</option>
        {/* <option value='CC'>CC</option>
        <option value='CD'>CD</option>
        <option value='CF'>CF</option>
        <option value='CG'>CG</option>
        <option value='CH'>CH</option>
        <option value='CI'>CI</option>
        <option value='CK'>CK</option> */}
        <option value='CL'>Chile</option>
        {/* <option value='CM'>CM</option>
        <option value='CN'>CN</option> */}
        <option value='CO'>Colombia</option>
        <option value='CR'>Costa Rica</option>
        <option value='CU'>Cuba</option>
        {/* <option value='CV'>CV</option>
        <option value='CW'>CW</option>
        <option value='CX'>CX</option>
        <option value='CY'>CY</option>
        <option value='CZ'>CZ</option>
        <option value='DE'>DE</option>
        <option value='DJ'>DJ</option>
        <option value='DK'>DK</option>
        <option value='DM'>DM</option> */}
        <option value='DO'>Republica Dominicana</option>
        {/* <option value='DZ'>Algeria</option> */}
        <option value='EC'>Ecuador</option>
        {/* <option value='EE'>EE</option>
        <option value='EG'>EG</option>
        <option value='EH'>EH</option>
        <option value='ER'>ER</option> */}
        <option value='ES'>España</option>
        {/* <option value='ET'>ET</option>
        <option value='FI'>FI</option>
        <option value='FJ'>FJ</option>
        <option value='FK'>FK</option>
        <option value='FM'>FM</option>
        <option value='FO'>FO</option>
        <option value='FR'>FR</option>
        <option value='GA'>GA</option> */}
        {/* <option value='GB'>Gran Bretaña</option> */}
        {/* <option value='GD'>GD</option>
        <option value='GE'>GE</option>
        <option value='GF'>GF</option>
        <option value='GG'>GG</option>
        <option value='GH'>GH</option>
        <option value='GI'>GI</option>
        <option value='GL'>GL</option>
        <option value='GM'>GM</option>
        <option value='GN'>GN</option>
        <option value='GP'>GP</option>
        <option value='GQ'>GQ</option>
        <option value='GR'>GR</option> */}
        <option value='GT'>Guatemala</option>
        {/* <option value='GU'>GU</option>
        <option value='GW'>GW</option> */}
        <option value='GY'>Guyana</option>
        {/* <option value='HK'>HK</option> */}
        <option value='HN'>Honduras</option>
        {/* <option value='HR'>HR</option> */}
        <option value='HT'>Haiti</option>
        {/* <option value='HU'>HU</option>
        <option value='ID'>ID</option>
        <option value='IE'>IE</option>
        <option value='IL'>IL</option>
        <option value='IM'>IM</option>
        <option value='IN'>IN</option>
        <option value='IO'>IO</option>
        <option value='IQ'>IQ</option>
        <option value='IR'>IR</option>
        <option value='IS'>IS</option>
        <option value='IT'>IT</option>
        <option value='JE'>JE</option>
        <option value='JM'>JM</option>
        <option value='JO'>JO</option>
        <option value='JP'>Japon</option>
        <option value='KE'>KE</option>
        <option value='KG'>KG</option>
        <option value='KH'>KH</option>
        <option value='KI'>KI</option>
        <option value='KM'>KM</option>
        <option value='KN'>KN</option>
        <option value='KP'>KP</option>
        <option value='KR'>KR</option>
        <option value='KW'>KW</option>
        <option value='KY'>KY</option>
        <option value='KZ'>KZ</option>
        <option value='LA'>LA</option>
        <option value='LB'>LB</option>
        <option value='LC'>LC</option>
        <option value='LI'>LI</option>
        <option value='LK'>LK</option>
        <option value='LR'>LR</option>
        <option value='LS'>LS</option>
        <option value='LT'>LT</option>
        <option value='LU'>LU</option>
        <option value='LV'>LV</option>
        <option value='LY'>LY</option>
        <option value='MA'>Morocco</option>
        <option value='MC'>Monaco</option>
        <option value='MD'>MD</option>
        <option value='ME'>Montenegro</option>
        <option value='MF'>MF</option>
        <option value='MG'>MG</option>
        <option value='MH'>MH</option>
        <option value='MK'>MK</option>
        <option value='ML'>ML</option>
        <option value='MM'>MM</option>
        <option value='MN'>Mongolia</option>
        <option value='MO'>MO</option>
        <option value='MP'>MP</option>
        <option value='MQ'>MQ</option>
        <option value='MR'>MR</option>
        <option value='MS'>Monserrat</option>
        <option value='MT'>MT</option>
        <option value='MU'>MU</option>
        <option value='MV'>MV</option>
        <option value='MW'>MW</option> */}
        <option value='MX'>Mexico</option>
        {/* <option value='MY'>MY</option>
        <option value='MZ'>Mozambique</option>
        <option value='NA'>NA</option>
        <option value='NC'>NC</option>
        <option value='NE'>NE</option>
        <option value='NF'>NF</option>
        <option value='NG'>NG</option> */}
        <option value='NI'>Nicaragua</option>
        {/* <option value='NL'>NL</option>
        <option value='NO'>NO</option>
        <option value='NP'>NP</option>
        <option value='NR'>NR</option>
        <option value='NU'>NU</option>
        <option value='NZ'>NZ</option>
        <option value='OM'>OM</option> */}
        <option value='PA'>Panama</option>
        <option value='PE'>Peru</option>
        {/* <option value='PF'>PF</option>
        <option value='PG'>PG</option>
        <option value='PH'>PH</option>
        <option value='PK'>PK</option>
        <option value='PL'>PL</option>
        <option value='PM'>PM</option> */}
        <option value='PR'>Puerto Rico</option>
        {/* <option value='PS'>PS</option>
        <option value='PT'>PT</option>
        <option value='PW'>PW</option> */}
        <option value='PY'>Paraguay</option>
        {/* <option value='QA'>QA</option>
        <option value='RE'>RE</option>
        <option value='RO'>RO</option>
        <option value='RS'>RS</option>
        <option value='RU'>RU</option>
        <option value='RW'>RW</option>
        <option value='SA'>SA</option>
        <option value='SB'>SB</option>
        <option value='SC'>SC</option>
        <option value='SD'>SD</option>
        <option value='SE'>SE</option>
        <option value='SG'>SG</option>
        <option value='SH'>SH</option>
        <option value='SI'>SI</option>
        <option value='SJ'>SJ</option>
        <option value='SK'>SK</option>
        <option value='SL'>SL</option>
        <option value='SM'>SM</option>
        <option value='SN'>SN</option>
        <option value='SO'>SO</option> */}
        <option value='SR'>Surinam</option>
        {/* <option value='SS'>SS</option>
        <option value='ST'>ST</option> */}
        <option value='SV'>El Salvador</option>
       {/*  <option value='SX'>SX</option>
        <option value='SY'>SY</option>
        <option value='SZ'>SZ</option>
        <option value='TA'>TA</option>
        <option value='TC'>TC</option>
        <option value='TD'>TD</option>
        <option value='TG'>TG</option>
        <option value='TH'>TH</option>
        <option value='TJ'>TJ</option>
        <option value='TK'>TK</option>
        <option value='TL'>Timor este</option>
        <option value='TM'>Turkeminstan</option>
        <option value='TN'>Tunisia</option>
        <option value='TO'>Tonga</option>
        <option value='TR'>Turkia</option> */}
        <option value='TT'>Trinidad y tobago</option>
        {/* <option value='TV'>Tuvalu</option>
        <option value='TW'>Taiwan</option>
        <option value='TZ'>Tanzania</option>
        <option value='UA'>Ukrania</option>
        <option value='UG'>Uganda</option> */}
        <option value='US'>Estados unidos</option>
        <option value='UY'>Uruguay</option>
        {/* <option value='UZ'>Uzbekistan</option>
        <option value='VA'>Vaticano</option>
        <option value='VC'>San vicente y las granadinas</option> */}
        <option value='VE'>Venezuela</option>
       {/*  <option value='VG'>Islas virgenes britanicas</option>
        <option value='VI'>Islas virgenes</option>
        <option value='VN'>Vietnam</option>
        <option value='VU'>Vanuatu</option>
        <option value='WS'>Samoa</option>
        <option value='YE'>Yemen</option>
        <option value='YT'>Mayotte</option>
        <option value='ZA'>Sud Africa</option>
        <option value='ZM'>Zambia</option>
        <option value='ZW'>Zimbabwe</option> */}
      </datalist>
    </>
  );
};

export default PhoneCodes;
